name: flex_with_main_child
description: A Flex (i.e. Column or Row) that sizes itself to its main child in the cross axis direction.
version: 0.2.0
repository: https://github.com/chomosuke/flex_with_main_child

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
